### ISSUE TITLE
How to use those files and change the shortcuts?

### ISSUE THREAD

**Issue by iamthehorse** [gillescastel/inkscape-shortcut-manager#1]
Could you tell me how to use those files? I have read your article carefully and tried my best to find the methods, but I still can not do anything about it. Thank you very much!

**Comment by Kateba72** [comment]
You have to run main.py before opening inkscape. Also, you need to install the [Xlib library](https://github.com/python-xlib/python-xlib).

I would also advise you to take a look at `vim.py`.
If you installed the latex snippets for vim in a way that only works for `.tex` files, you have to change line 9 to `f = tempfile.NamedTemporaryFile(mode='w+', delete=False, suffix='.tex')` 
The functionality for opening vim assumes that you have `urxvt` installed, you may want to do this or change the terminal emulator. Also, vim will use the file `~/.minimal-tex-vimrc`. Create it or delete the line.
Also, later in the file, when the latex document you wrote is compiled, the program adds some packages. You may want to change them, too.

**Comment by gillescastel** [comment]
I expanded the readme and made the shortcut manager configurable!
