### ISSUE TITLE
What happens when a style is saved?

### ISSUE THREAD

**Issue by sturgman** [gillescastel/inkscape-shortcut-manager#11]
Could you explain what happens when a style is saved? Inkscape does not have a "style library" functionality as far as I know. Are you defining the styles in some kind of svg file and importing them somehow? Thank you!

**Comment by gillescastel** [comment]
The code responsible for savings styles / objects is located in the `styles.py` file.




First, the code copies the object by pressing Ctrl+C:

https://github.com/gillescastel/inkscape-shortcut-manager/blob/da65ba20709e4d2d1116669efa219bfbeb8ed0ed/styles.py#L79

Then the `get(TARGET)` retrieves the content from the clipboard in the format specified by `TARGET`, which is a constant equal to `'image/x-inkscape-svg'`. So this retrieves the svg code for the object.

Then the code writes this svg to a file located in the configuration directory (`~/.config/inkscape-shortcut-manager/objects/name.svg` or `/styles/name.svg`)

https://github.com/gillescastel/inkscape-shortcut-manager/blob/da65ba20709e4d2d1116669efa219bfbeb8ed0ed/styles.py#L105

When you apply a style, this file gets copied to your clipboard and the program presses `Ctrl+Shift+V`, which is 'paste style'.

Hopes this clears things up a bit!

**Comment by sturgman** [comment]
That is awesome. Thank you so much for the explanation!
