### ISSUE TITLE
Shortcut key chords with three keypresses not working

### ISSUE THREAD

**Issue by inigohidalgo** [gillescastel/inkscape-shortcut-manager#16]
When I try to use a key chord with thee key presses, only the first two are recognized as part of the chord, and the third is passed to inkscape.

For example `a` + `g` + `d` should get a thickly dotted arrow, as you explain in your [blog post](https://castel.dev/post/lecture-notes-2/#key-chords-to-apply-commonly-used-styles), but instead only `a`+`g` is recognized in the first instance, and `d` is passed to inkscape to bring up the dropper tool, resulting in only a thick solid arrow.

Another example where this is happening is `f` + `h` + `e` for filled and very thickly dashed, where instead it detects only `f` + `h` for a solid filled thick rectangle and the ellipse tool is brought up with the `e` keypress.

I don't know if this is intended behavior now since your post is over a year old now and this could have changed, in which case I can happily work with combinations of two keypresses.

**Comment by gillescastel** [comment]
Hi @inigohidalgo, thanks for this issue!

As you mentioned, `a` + `g` + `d` should indeed give you a thickly dotted arrow. With my machine / keyboard, that works. That issue may lie with the keyboard you're using. [Some keyboards have trouble detecting multiple keystrokes at once](https://www.wikiwand.com/en/Rollover_(key)), especially if the keys you're pressing are close together. You can test this for your keyboard here: http://random.xem.us/rollover.html. Try pressing a, g and d simultaneously. Please let me know if that's indeed the problem!

**Comment by inigohidalgo** [comment]
Hi @gillescastel thank you for replying so quickly!
The problem was simpler than that: I didn't realize the keystrokes had to be simultaneous. For some reason I thought they were sequential. The program is 100% running as intended.

Thank you so much for such an amazing program by the way, I am starting a new master's program and this will be incredibly useful!

**Comment by gillescastel** [comment]
Glad it works!
