### ISSUE TITLE
Running main.py

### ISSUE THREAD

**Issue by kylemonette** [gillescastel/inkscape-shortcut-manager#2]
When I run main.py, using the advice of the previous issue comment (user kateba72), I get the following error: 
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from normal import normal_mode
  File "/home/kylenew/inkscape-shortcut-manager/normal.py", line 140
    style['marker-end'] = f'url(#marker-arrow-{w})'
                                                  ^
SyntaxError: invalid syntax

I used git clone to download the files that were uploaded here. Was this the wrong approach? Why am I getting this error? Other files in the repository are having similar syntax errors.

**Comment by gillescastel** [comment]
What version of python are you using? Anything lower than 3.6 won't work.

**Comment by kylemonette** [comment]
2.7, which was the default on Ubuntu. How do I force it to use 3.6? (Sorry for the newbie questions but I really appreciate the help!)

**Comment by kylemonette** [comment]
Now when I run main.py (using 3.6), it appears to get stuck and do nothing. If I press control-c to cancel it, the following appears. 
`Traceback (most recent call last):
  File "main.py", line 91, in <module>
    main()
  File "main.py", line 78, in main
    evt = disp.next_event()
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 187, in next_event
    return self.display.next_event()
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 218, in next_event
    self.send_and_recv(event = 1)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 562, in send_and_recv
    rs, ws, es = select.select([self.socket], writeset, [], timeout)
`
I have no idea what to do here.

**Comment by gillescastel** [comment]
It waits for an Inkscape window to be opened. Upon opening one, it should print "Listening".
