### ISSUE TITLE
Shortcut Manager not detecting the Inkscape window

### ISSUE THREAD

**Issue by vadim-tch** [gillescastel/inkscape-shortcut-manager#31]
I have downloaded the script and copied the `config.py` file from examples into `~/.conifg/inkscape-shortcut-manager`.

However, when the shortcut manager is launched, it prints `{'style': PosixPath('/home/...'), 'object': PosixPath('/home/...')}` and then nothing happens. None of the shortcuts work In the Inscape window and no keystrokes are intercepted. I have tried running Inkscape both before and after starting the script.

It seems as though the script doesn't detect the window at all: an Inkscape window is never passed to the `is_inkscape()` function.

I have also tried installing `urxvt` according to the advice from another issue, this did not change anything. The issue seems to be identical to #25, but I'm using Linux.

I'm running Fedora 36 with Gnome 42. with Python 3.10.7, all dependencies are installed

**Comment by vadim-tch** [comment]
I've investigated it a bit and it seems like this is caused by Inkscape itself not setting some window parameters properly  - things like `wmctrl`, `xlsclients`, and `xwininfo` also can't see it.

@gillescastel, are you using an older version of Inkscape? Mine is 1.2.1 from the default Fedora RPM repo
Using the latest development version from the website also doesn't fix the problem

**Comment by Mohammed-Taher** [comment]
Same problem here, on Manjaro with Gnome 42.5 with Python 3.10.7. 
`wmctrl` can not find Inkscape.

**Comment by vadim-tch** [comment]
Solved — even though it seems to work with a lot of other applications under Wayland, it does not work with Inkscape.
Switching to Xorg solves the issue.
